version: '2.2'

services:

  postgres-app:
    container_name: postgres-app
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./db/postgres/data:/data/postgres
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  inventory-service:
    container_name: inventory-service
    image: b10623041/inventory-service
    depends_on:
      - postgres-app

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/image:/image
    depends_on:
      - inventory-service

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
    command: [ "--config=/etc/config.yaml" ]
    volumes:
      - ./otel/collector/config.yaml:/etc/config.yaml
    depends_on:
      - inventory-service



