server:
  port: ${MY_SERVER_PORT}

spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: classpath:/static/application-common.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/shopping-application
          jwk-set-uri: ${AUTH_SERVER_URL}/realms/shopping-application/protocol/openid-connect/certs
#  cloud:
#    function:
#      definition: addproduct
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9093
#      bindings:
#        addproduct-in-0:
#          group: add_product_group
#          destination: add-product
#          consumer:
#            partitioned: true
#            concurrency: 3

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
#    hostname: ${HOSTNAME}
    prefer-ip-address: true
    ip-address: 18.183.39.177
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
#  level:
#    org.springframework: DEBUG



