version: '2.2'

services:

  #  keycloak-mysql:
  #    container_name: keycloak-mysql
  #    image: mysql
  #    volumes:
  #      - ./db/mysql/keycloak:/var/lib/mysql
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: keycloak
  #      MYSQL_USER: keycloak
  #      MYSQL_PASSWORD: ${DB_PASSWORD}

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    command:
      - "start-dev --import-realm"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    #      DB_VENDOR: MYSQL
    #      DB_ADDR: mysql
    #      DB_DATABASE: keycloak
    #      DB_USER: keycloak
    #      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8078:8080"
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import/
  #    depends_on:
  #      - keycloak-mysql

  discovery-server:
    container_name: discovery-server
    image: b10623041/discovery-server
    ports:
      - "9500:9500"

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/image:/image
    depends_on:
      - keycloak
      - discovery-server